# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - 5.5.9
  - 5.6
  - 5.6.5
  - hhvm

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - composer install --prefer-source --no-interaction --dev
